# Generated by Django 3.2.12 on 2022-02-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iloveme', '0003_auto_20220218_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='pic_alt',
            field=models.TextField(default=''),
        ),
    ]
