# Generated by Django 3.2.12 on 2022-02-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(editable=False)),
                ('link', models.TextField(editable=False)),
                ('token', models.TextField(editable=False, unique=True)),
            ],
        ),
    ]
