# Generated by Django 3.2.12 on 2022-02-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captcha',
            old_name='link',
            new_name='url',
        ),
    ]
