# Generated by Django 3.2.12 on 2022-02-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20220218_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='captcha',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
    ]
